### ISSUE TITLE
'appendChild' error when running tests in cypress cloud, but tests run locally without issues

### ISSUE THREAD

**Issue by constantlyk** [Brugui7/cypress-log-filter#4]
hoping this is a stupid mistake on my part!

essentially, running tests in a cypress repo that uses cypress-log-filter works just fine locally, but the same setup fails when `--record`ing the run to cypress cloud.

more detail and repro steps here: https://github.com/constantlyk/cypress-cloud-filter

other notes:
- i am using the javascript version of cypress
- removing the `import 'cypress-log-filter` line allows the tests to run in cypress cloud, but also completely disables log filtering
- including `require('cypress-log-filter')` seems to have no effect
- this is replicable with electron and chrome browsers, headed and headless
- i haven't asked the cypress folx about this yet

**Comment by Brugui7** [comment]
After taking a look I can't see a way to add the filter in Cypress cloud due to the way the test recording is encapsulated.

For now I'll add a check so it doesn't break the test.

**Comment by Brugui7** [comment]
Should be fixed in 507abfd4ce6094673e147464744a7de21a9e0287.

**Comment by Brugui7** [comment]
Fixed and released in https://github.com/Brugui7/cypress-log-filter/releases/tag/1.0.5

**Comment by constantlyk** [comment]
@Brugui7 thank you, that worked! 

as you said, tests that run in cypress cloud can't use log filtering. but log filtering works as promised in the cypress test runner (which is where it is most useful to me, anyways), and using cypress-log-filter does not break cypress cloud tests as it was doing before. 👏🏻👏🏻
